#!/bin/sh
#
#  Join the contents of files in a directory to make a unified file.

if [ "$#" -ne 1 ]
then
   echo usage $0 '<directory>'
   exit 1
fi
DIR="$1"
if [ ! -d "$DIR" ]
then
   echo Directory '"'$DIR'"' does not exist.
   exit 1
fi

cat `find $DIR -maxdepth 1 -type f | sort -r`
