#!/bin/bash
#
#  Add a new Debian changelog entry.

if [ -z "$VERSION" ]; then
   echo "ERROR: VERSION environment variable is not set!"
   exit 1
fi

CHANGELOGFILE=debian/changelog
if [ "$VERSION" != "${VERSION#2}" ]; then
   CHANGELOGFILE=debian/changelog-commercial
fi

if grep -q -w '\('"$VERSION"'\)' "$CHANGELOGFILE"; then
   echo "ERROR: Version $VERSION already in $CHANGELOGFILE!"
   exit 1
fi

cat <<@EOF >"$CHANGELOGFILE".new
vpostmaster ($VERSION) stable; urgency=low

  * New upstream version.  See WHATSNEW.

 -- Sean Reifschneider <jafo@tummy.com>  `date "+%a, %d %b %Y %H:%M:%S %z"`

@EOF
cat "$CHANGELOGFILE" >>"$CHANGELOGFILE".new
cat "$CHANGELOGFILE".new >"$CHANGELOGFILE"
rm -f "$CHANGELOGFILE".new

echo "======================================"
echo "GIT DIFF"
echo "======================================"
git diff
